"""new db

Revision ID: 0f0daacb2a5d
Revises: 
Create Date: 2020-04-28 21:29:07.463473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0daacb2a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('updated', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_country'), 'stats', ['country'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_country'), table_name='stats')
    op.drop_table('stats')
    # ### end Alembic commands ###
